server:
  port: 8080
spring:    
  application:
    name: aggregator_service
    
reservation_service: reservation_service
airport_service: airport_service
auth_service: auth_service
quartz_email_service: quartz_email_service